apiVersion: v1
kind: Pod
metadata:
  name: volume-pod
  labels:
    name: volume-pod
spec:
  volumes:
    - name: vol1

  containers:
  - name: myapp
    image: nginx:1.7.9
    volumeMounts:
      - name: vol1
        mountPath: "/data"
        readOnly: false
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
