apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      name: volume-pod3

---
apiVersion: v1
kind: Pod
metadata:
  name: volume-pod3
  labels:
    name: volume-pod3
spec:
  volumes:
    - name: vol1
      persistentVolumeClaim:
        claimName: pvc1
  containers:
  - name: myapp2
    image: nginx:1.7.9
    volumeMounts:
      - name: vol1
        mountPath: "/data"
        readOnly: false
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
