apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa1
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef: 
    kind: Deployment
    name: myweb1
  targetCPUUtilizationPercentage: 80
