apiVersion: v1
kind: Pod
metadata:
  name: web1
  labels:
    name: web1
spec:
  containers:
  - name: web1
    image: nginx:1.7.9
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
