apiVersion: v1
kind: ConfigMap
metadata:
  name: dbconfig
data:
  MYSQL_DATABASE : db1
  MYSQL_USER: dbuser
  MYSQL_PASSWORD : pass@123456
  MYSQL_ROOT_PASSWORD: Pass@Root1
---
apiVersion: v1
kind: Pod
metadata:
  name: config-pod
spec:
  containers:
    - image: mysql:5.7
      name: db
      envFrom:
        - configMapRef: 
            name: dbconfig

## To deploy configmap
# $ kubectl apply -f configmap1.yaml

## To Test it
# $ kubectl exec -it config-pod sh
# $ mysql -umahendra -p
# Enter Password: pass@123456 
# exit 
# exit


