## To generate SECRET, use base64 utility to encrypt values
apiVersion: v1
kind: Secret
metadata:
  name: secret1
data:
  MYSQL_DATABASE : ZGIxCg==
  MYSQL_USER: ZGJ1c2VyCg==
  MYSQL_PASSWORD : cGFzc0AxMjM0NTYK
  MYSQL_ROOT_PASSWORD: UGFzc0BSb290MQo=
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
    - image: mysql:5.7
      name: db
      envFrom:
        - secretRef: 
            name: secret1

## To deploy secret
# $ kubectl apply -f secret1.yaml

## To Test it
# $ kubectl exec -it secret-pod sh
# $ mysql -umahendra -p
# Enter Password: pass@123456 
# exit 
# exit


